### ISSUE TITLE
txpool_status does not exist

### ISSUE THREAD

**Issue by remyroy** [samcm/ethereum-metrics-exporter#21]
It seems like this project is calling a txpool_status method on the execution RPC endpoing which does not exist on Geth 1.10.18-stable.

Geth is complaining with these messages in the log:
```
WARN [06-06|19:45:59.953] Served txpool_status                     conn=127.0.0.1:55350 reqid=0 duration="37.21µs"   err="the method txpool_status does not exist/is not available"
```

**Comment by samcm** [comment]
Thanks for the issue :)

This is because the txpool module/namespace isn't enabled by defauit I think. Either way, have disabled it by default in the exporter, it can be enabled with the config file or with `--execution-modules=net,eth,web3,txpool` 👌 

Resolved in: https://github.com/samcm/ethereum-metrics-exporter/pull/23

**Comment by remyroy** [comment]
Thanks for the info and the response.
